import { jsPDF } from "jspdf";

export type PlatformInvoiceDoc = {
  id: string;
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  periodLabel: string;
  billingCycle: string;
  currency: string;
  studentsBilled: number;
  ratePerStudent: number;
  subtotal: number;
  discountPercent: number;
  discountAmount: number;
  taxPercent: number;
  taxAmount: number;
  total: number;
  status: string;
  paymentMethod?: string | null;
  paidAt?: string | null;
  paymentRef?: string | null;
  receiptNumber?: string | null;
  notes?: string | null;
  tenantId?: string | null;
  tenantName?: string | null;
};

const CURRENCY_SYMBOL: Record<string, string> = {
  INR: "₹",
  USD: "$",
  EUR: "€",
};

function money(currency: string, amount: number) {
  const sym = CURRENCY_SYMBOL[currency] ?? `${currency} `;
  return `${sym}${Math.round(amount).toLocaleString("en-IN")}`;
}

function drawHeader(doc: jsPDF, title: string, subtitle: string) {
  doc.setFillColor(15, 118, 110);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title, 14, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(subtitle, 14, 22);
  doc.setTextColor(15, 23, 42);
}

function drawPartyBlock(
  doc: jsPDF,
  y: number,
  leftTitle: string,
  leftLines: string[],
  rightTitle: string,
  rightLines: string[],
) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(leftTitle.toUpperCase(), 14, y);
  doc.text(rightTitle.toUpperCase(), 110, y);
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  let ly = y + 6;
  leftLines.forEach((line) => {
    doc.text(line, 14, ly);
    ly += 5;
  });
  let ry = y + 6;
  rightLines.forEach((line) => {
    doc.text(line, 110, ry);
    ry += 5;
  });
  return Math.max(ly, ry) + 4;
}

export function downloadPlatformInvoicePdf(
  invoice: PlatformInvoiceDoc,
  opts?: { schoolHost?: string },
) {
  const doc = new jsPDF();
  const school = invoice.tenantName || "School tenant";
  drawHeader(doc, "TAX INVOICE", `${invoice.invoiceNumber} · ${invoice.status}`);

  let y = 38;
  y = drawPartyBlock(
    doc,
    y,
    "Billed to",
    [
      school,
      invoice.tenantId ? `Tenant ${invoice.tenantId}` : "",
      opts?.schoolHost || "",
    ].filter(Boolean),
    "From",
    ["School Accounts Platform", "SaaS subscription billing", "support@schoolaccounts.in"],
  );

  doc.setFontSize(10);
  doc.text(`Issue date: ${invoice.issueDate}`, 14, y);
  doc.text(`Due date: ${invoice.dueDate}`, 110, y);
  y += 6;
  doc.text(`Period: ${invoice.periodLabel || invoice.billingCycle}`, 14, y);
  doc.text(`Cycle: ${invoice.billingCycle}`, 110, y);
  y += 10;

  doc.setFillColor(244, 244, 245);
  doc.roundedRect(14, y, 182, 42, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Line items", 18, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(
    `Seat licence · ${invoice.studentsBilled.toLocaleString("en-IN")} students × ${money(invoice.currency, invoice.ratePerStudent)}`,
    18,
    y + 16,
  );
  doc.text(`Subtotal  ${money(invoice.currency, invoice.subtotal)}`, 18, y + 24);
  doc.text(
    `Discount (${invoice.discountPercent}%)  −${money(invoice.currency, invoice.discountAmount)}`,
    18,
    y + 30,
  );
  doc.text(
    `Tax / GST (${invoice.taxPercent}%)  ${money(invoice.currency, invoice.taxAmount)}`,
    18,
    y + 36,
  );
  y += 52;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(15, 118, 110);
  doc.text(`Total due  ${money(invoice.currency, invoice.total)}`, 14, y);
  doc.setTextColor(15, 23, 42);
  y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  if (invoice.notes) doc.text(`Notes: ${invoice.notes}`, 14, y);
  doc.text("Generated by School Accounts Control Plane", 14, 285);

  doc.save(`${invoice.invoiceNumber}.pdf`);
}

export function downloadPlatformReceiptPdf(
  invoice: PlatformInvoiceDoc,
  opts?: { schoolHost?: string },
) {
  if (invoice.status !== "Paid" || !invoice.receiptNumber) {
    throw new Error("Receipt is only available for paid invoices");
  }
  const doc = new jsPDF();
  const school = invoice.tenantName || "School tenant";
  drawHeader(doc, "PAYMENT RECEIPT", `${invoice.receiptNumber} · Paid`);

  let y = 38;
  y = drawPartyBlock(
    doc,
    y,
    "Received from",
    [
      school,
      invoice.tenantId ? `Tenant ${invoice.tenantId}` : "",
      opts?.schoolHost || "",
    ].filter(Boolean),
    "Received by",
    ["School Accounts Platform", "Subscription settlement", "accounts@schoolaccounts.in"],
  );

  doc.setFontSize(10);
  doc.text(`Invoice: ${invoice.invoiceNumber}`, 14, y);
  doc.text(`Paid at: ${invoice.paidAt ? String(invoice.paidAt).slice(0, 16).replace("T", " ") : "—"}`, 110, y);
  y += 6;
  doc.text(`Method: ${invoice.paymentMethod || "—"}`, 14, y);
  doc.text(`Reference: ${invoice.paymentRef || "—"}`, 110, y);
  y += 6;
  doc.text(`Period: ${invoice.periodLabel || invoice.billingCycle}`, 14, y);
  y += 12;

  doc.setFillColor(204, 251, 241);
  doc.roundedRect(14, y, 182, 36, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 118, 110);
  doc.text("Amount received", 18, y + 12);
  doc.setFontSize(18);
  doc.text(money(invoice.currency, invoice.total), 18, y + 26);
  doc.setTextColor(15, 23, 42);

  y += 48;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Covers ${invoice.studentsBilled.toLocaleString("en-IN")} seats · ${invoice.billingCycle} licence`,
    14,
    y,
  );
  doc.text("Thank you for your payment. This receipt confirms settlement of the invoice above.", 14, y + 8);
  doc.text("Generated by School Accounts Control Plane", 14, 285);

  doc.save(`${invoice.receiptNumber}.pdf`);
}
