/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpersonateRouteImport } from './routes/impersonate'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as TenantStudentsRouteImport } from './routes/tenant/students'
import { Route as TenantStaffRouteImport } from './routes/tenant/staff'
import { Route as TenantSettingsRouteImport } from './routes/tenant/settings'
import { Route as TenantNotificationsRouteImport } from './routes/tenant/notifications'
import { Route as TenantFinanceRouteImport } from './routes/tenant/finance'
import { Route as TenantDashboardRouteImport } from './routes/tenant/dashboard'
import { Route as TenantBillingRouteImport } from './routes/tenant/billing'
import { Route as SuperAdminTenantsRouteImport } from './routes/super-admin/tenants'
import { Route as SuperAdminSupportRouteImport } from './routes/super-admin/support'
import { Route as SuperAdminPlansRouteImport } from './routes/super-admin/plans'
import { Route as SuperAdminOverviewRouteImport } from './routes/super-admin/overview'
import { Route as SuperAdminSupportIndexRouteImport } from './routes/super-admin/support/index'
import { Route as TenantStudentsAdmitRouteImport } from './routes/tenant/students_.admit'
import { Route as SuperAdminSupportHelpRouteImport } from './routes/super-admin/support/help'
import { Route as SuperAdminSupportContactRouteImport } from './routes/super-admin/support/contact'
import { Route as SuperAdminSupportTicketIdRouteImport } from './routes/super-admin/support/$ticketId'
import { Route as ParentStudentTokenRouteImport } from './routes/parent/student.$token'

const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonateRoute = ImpersonateRouteImport.update({
  id: '/impersonate',
  path: '/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const TenantStudentsRoute = TenantStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStaffRoute = TenantStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSettingsRoute = TenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TenantRoute,
} as any)
const TenantNotificationsRoute = TenantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TenantRoute,
} as any)
const TenantFinanceRoute = TenantFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => TenantRoute,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBillingRoute = TenantBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TenantRoute,
} as any)
const SuperAdminTenantsRoute = SuperAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSupportRoute = SuperAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPlansRoute = SuperAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminOverviewRoute = SuperAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSupportIndexRoute = SuperAdminSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminSupportRoute,
} as any)
const TenantStudentsAdmitRoute = TenantStudentsAdmitRouteImport.update({
  id: '/students_/admit',
  path: '/students/admit',
  getParentRoute: () => TenantRoute,
} as any)
const SuperAdminSupportHelpRoute = SuperAdminSupportHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => SuperAdminSupportRoute,
} as any)
const SuperAdminSupportContactRoute =
  SuperAdminSupportContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => SuperAdminSupportRoute,
  } as any)
const SuperAdminSupportTicketIdRoute =
  SuperAdminSupportTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => SuperAdminSupportRoute,
  } as any)
const ParentStudentTokenRoute = ParentStudentTokenRouteImport.update({
  id: '/parent/student/$token',
  path: '/parent/student/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/super-admin/overview': typeof SuperAdminOverviewRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/support': typeof SuperAdminSupportRouteWithChildren
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/finance': typeof TenantFinanceRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/staff': typeof TenantStaffRoute
  '/tenant/students': typeof TenantStudentsRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/parent/student/$token': typeof ParentStudentTokenRoute
  '/super-admin/support/$ticketId': typeof SuperAdminSupportTicketIdRoute
  '/super-admin/support/contact': typeof SuperAdminSupportContactRoute
  '/super-admin/support/help': typeof SuperAdminSupportHelpRoute
  '/tenant/students/admit': typeof TenantStudentsAdmitRoute
  '/super-admin/support/': typeof SuperAdminSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin/overview': typeof SuperAdminOverviewRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/finance': typeof TenantFinanceRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/staff': typeof TenantStaffRoute
  '/tenant/students': typeof TenantStudentsRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/parent/student/$token': typeof ParentStudentTokenRoute
  '/super-admin/support/$ticketId': typeof SuperAdminSupportTicketIdRoute
  '/super-admin/support/contact': typeof SuperAdminSupportContactRoute
  '/super-admin/support/help': typeof SuperAdminSupportHelpRoute
  '/tenant/students/admit': typeof TenantStudentsAdmitRoute
  '/super-admin/support': typeof SuperAdminSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/super-admin/overview': typeof SuperAdminOverviewRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/support': typeof SuperAdminSupportRouteWithChildren
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/finance': typeof TenantFinanceRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/staff': typeof TenantStaffRoute
  '/tenant/students': typeof TenantStudentsRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/parent/student/$token': typeof ParentStudentTokenRoute
  '/super-admin/support/$ticketId': typeof SuperAdminSupportTicketIdRoute
  '/super-admin/support/contact': typeof SuperAdminSupportContactRoute
  '/super-admin/support/help': typeof SuperAdminSupportHelpRoute
  '/tenant/students_/admit': typeof TenantStudentsAdmitRoute
  '/super-admin/support/': typeof SuperAdminSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/impersonate'
    | '/login'
    | '/reset-password'
    | '/super-admin'
    | '/tenant'
    | '/super-admin/overview'
    | '/super-admin/plans'
    | '/super-admin/support'
    | '/super-admin/tenants'
    | '/tenant/billing'
    | '/tenant/dashboard'
    | '/tenant/finance'
    | '/tenant/notifications'
    | '/tenant/settings'
    | '/tenant/staff'
    | '/tenant/students'
    | '/super-admin/'
    | '/tenant/'
    | '/parent/student/$token'
    | '/super-admin/support/$ticketId'
    | '/super-admin/support/contact'
    | '/super-admin/support/help'
    | '/tenant/students/admit'
    | '/super-admin/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/impersonate'
    | '/login'
    | '/reset-password'
    | '/super-admin/overview'
    | '/super-admin/plans'
    | '/super-admin/tenants'
    | '/tenant/billing'
    | '/tenant/dashboard'
    | '/tenant/finance'
    | '/tenant/notifications'
    | '/tenant/settings'
    | '/tenant/staff'
    | '/tenant/students'
    | '/super-admin'
    | '/tenant'
    | '/parent/student/$token'
    | '/super-admin/support/$ticketId'
    | '/super-admin/support/contact'
    | '/super-admin/support/help'
    | '/tenant/students/admit'
    | '/super-admin/support'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/impersonate'
    | '/login'
    | '/reset-password'
    | '/super-admin'
    | '/tenant'
    | '/super-admin/overview'
    | '/super-admin/plans'
    | '/super-admin/support'
    | '/super-admin/tenants'
    | '/tenant/billing'
    | '/tenant/dashboard'
    | '/tenant/finance'
    | '/tenant/notifications'
    | '/tenant/settings'
    | '/tenant/staff'
    | '/tenant/students'
    | '/super-admin/'
    | '/tenant/'
    | '/parent/student/$token'
    | '/super-admin/support/$ticketId'
    | '/super-admin/support/contact'
    | '/super-admin/support/help'
    | '/tenant/students_/admit'
    | '/super-admin/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImpersonateRoute: typeof ImpersonateRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TenantRoute: typeof TenantRouteWithChildren
  ParentStudentTokenRoute: typeof ParentStudentTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonate': {
      id: '/impersonate'
      path: '/impersonate'
      fullPath: '/impersonate'
      preLoaderRoute: typeof ImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/tenant/students': {
      id: '/tenant/students'
      path: '/students'
      fullPath: '/tenant/students'
      preLoaderRoute: typeof TenantStudentsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/staff': {
      id: '/tenant/staff'
      path: '/staff'
      fullPath: '/tenant/staff'
      preLoaderRoute: typeof TenantStaffRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/settings': {
      id: '/tenant/settings'
      path: '/settings'
      fullPath: '/tenant/settings'
      preLoaderRoute: typeof TenantSettingsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/notifications': {
      id: '/tenant/notifications'
      path: '/notifications'
      fullPath: '/tenant/notifications'
      preLoaderRoute: typeof TenantNotificationsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/finance': {
      id: '/tenant/finance'
      path: '/finance'
      fullPath: '/tenant/finance'
      preLoaderRoute: typeof TenantFinanceRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/dashboard': {
      id: '/tenant/dashboard'
      path: '/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/billing': {
      id: '/tenant/billing'
      path: '/billing'
      fullPath: '/tenant/billing'
      preLoaderRoute: typeof TenantBillingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/super-admin/tenants': {
      id: '/super-admin/tenants'
      path: '/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof SuperAdminTenantsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/support': {
      id: '/super-admin/support'
      path: '/support'
      fullPath: '/super-admin/support'
      preLoaderRoute: typeof SuperAdminSupportRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/plans': {
      id: '/super-admin/plans'
      path: '/plans'
      fullPath: '/super-admin/plans'
      preLoaderRoute: typeof SuperAdminPlansRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/overview': {
      id: '/super-admin/overview'
      path: '/overview'
      fullPath: '/super-admin/overview'
      preLoaderRoute: typeof SuperAdminOverviewRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/support/': {
      id: '/super-admin/support/'
      path: '/'
      fullPath: '/super-admin/support/'
      preLoaderRoute: typeof SuperAdminSupportIndexRouteImport
      parentRoute: typeof SuperAdminSupportRoute
    }
    '/tenant/students_/admit': {
      id: '/tenant/students_/admit'
      path: '/students/admit'
      fullPath: '/tenant/students/admit'
      preLoaderRoute: typeof TenantStudentsAdmitRouteImport
      parentRoute: typeof TenantRoute
    }
    '/super-admin/support/help': {
      id: '/super-admin/support/help'
      path: '/help'
      fullPath: '/super-admin/support/help'
      preLoaderRoute: typeof SuperAdminSupportHelpRouteImport
      parentRoute: typeof SuperAdminSupportRoute
    }
    '/super-admin/support/contact': {
      id: '/super-admin/support/contact'
      path: '/contact'
      fullPath: '/super-admin/support/contact'
      preLoaderRoute: typeof SuperAdminSupportContactRouteImport
      parentRoute: typeof SuperAdminSupportRoute
    }
    '/super-admin/support/$ticketId': {
      id: '/super-admin/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/super-admin/support/$ticketId'
      preLoaderRoute: typeof SuperAdminSupportTicketIdRouteImport
      parentRoute: typeof SuperAdminSupportRoute
    }
    '/parent/student/$token': {
      id: '/parent/student/$token'
      path: '/parent/student/$token'
      fullPath: '/parent/student/$token'
      preLoaderRoute: typeof ParentStudentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperAdminSupportRouteChildren {
  SuperAdminSupportTicketIdRoute: typeof SuperAdminSupportTicketIdRoute
  SuperAdminSupportContactRoute: typeof SuperAdminSupportContactRoute
  SuperAdminSupportHelpRoute: typeof SuperAdminSupportHelpRoute
  SuperAdminSupportIndexRoute: typeof SuperAdminSupportIndexRoute
}

const SuperAdminSupportRouteChildren: SuperAdminSupportRouteChildren = {
  SuperAdminSupportTicketIdRoute: SuperAdminSupportTicketIdRoute,
  SuperAdminSupportContactRoute: SuperAdminSupportContactRoute,
  SuperAdminSupportHelpRoute: SuperAdminSupportHelpRoute,
  SuperAdminSupportIndexRoute: SuperAdminSupportIndexRoute,
}

const SuperAdminSupportRouteWithChildren =
  SuperAdminSupportRoute._addFileChildren(SuperAdminSupportRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminOverviewRoute: typeof SuperAdminOverviewRoute
  SuperAdminPlansRoute: typeof SuperAdminPlansRoute
  SuperAdminSupportRoute: typeof SuperAdminSupportRouteWithChildren
  SuperAdminTenantsRoute: typeof SuperAdminTenantsRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminOverviewRoute: SuperAdminOverviewRoute,
  SuperAdminPlansRoute: SuperAdminPlansRoute,
  SuperAdminSupportRoute: SuperAdminSupportRouteWithChildren,
  SuperAdminTenantsRoute: SuperAdminTenantsRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface TenantRouteChildren {
  TenantBillingRoute: typeof TenantBillingRoute
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantFinanceRoute: typeof TenantFinanceRoute
  TenantNotificationsRoute: typeof TenantNotificationsRoute
  TenantSettingsRoute: typeof TenantSettingsRoute
  TenantStaffRoute: typeof TenantStaffRoute
  TenantStudentsRoute: typeof TenantStudentsRoute
  TenantIndexRoute: typeof TenantIndexRoute
  TenantStudentsAdmitRoute: typeof TenantStudentsAdmitRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantBillingRoute: TenantBillingRoute,
  TenantDashboardRoute: TenantDashboardRoute,
  TenantFinanceRoute: TenantFinanceRoute,
  TenantNotificationsRoute: TenantNotificationsRoute,
  TenantSettingsRoute: TenantSettingsRoute,
  TenantStaffRoute: TenantStaffRoute,
  TenantStudentsRoute: TenantStudentsRoute,
  TenantIndexRoute: TenantIndexRoute,
  TenantStudentsAdmitRoute: TenantStudentsAdmitRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImpersonateRoute: ImpersonateRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TenantRoute: TenantRouteWithChildren,
  ParentStudentTokenRoute: ParentStudentTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
